
services:
  # Laravel App (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: notification-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html       # Código fuente
      - vendor_data:/var/www/html/vendor  # Vendor persistente
    networks:
      - notification-net
    depends_on:
      - db
      - redis

  # Webserver (Nginx)
  webserver:
    image: nginx:alpine
    container_name: notification-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - notification-net
    depends_on:
      - app

  # Base de datos
  db:
    image: postgres:15
    container_name: notification-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: notification_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - notification-net

  # Redis (cache y colas)
  redis:
    image: redis:alpine
    container_name: notification-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - notification-net

# Volúmenes persistentes
volumes:
  db_data:
  vendor_data:

networks:
  notification-net:
    driver: bridge
